(cl:in-package airsim_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          UAV-VAL
          UAV
          GRAFO-VAL
          GRAFO
          EDGES-VAL
          EDGES
          TX-VAL
          TX
          TY-VAL
          TY
          THETA-VAL
          THETA
          SCALE-VAL
          SCALE
          THETA_OFFSET-VAL
          THETA_OFFSET
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          CAMERA_TYPE-VAL
          CAMERA_TYPE
          FILENAME-VAL
          FILENAME
          IMAGE-VAL
          IMAGE
))